language: android
android:
  components:
      # The BuildTools version used by your project
      - build-tools-22.0.0
      # The SDK version used to compile your project
      - android-22
      # Additional components
      - extra-android-m2repository

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
install: ./gradlew clean
#script: ./gradlew check
